macro(enable_gtest)
  if(NOT "${GTEST_FOUND}")
    find_package(GTest)
    find_package(Threads)
  endif()
  if(NOT "${GTEST_FOUND}")
    include(cmake/common/ExternalProjectAdd_GTest.cmake)
  endif()
  if(NOT "${GTEST_FOUND}")
    message(FATAL_ERROR "Could not find GTest.")
  endif()
endmacro()

macro(enable_picojson)
  if(NOT "${PICOJSON_FOUND}")
    include(cmake/common/ExternalProjectAdd_PicoJSON.cmake)
  endif()
  if(NOT "${PICOJSON_FOUND}")
    message(FATAL_ERROR "Could not find PicoJSON.")
  endif()
endmacro()
