macro(enable_gtest)
  if(NOT "${GTEST_FOUND}")
    find_package(GTest)
  endif()
  if(NOT "${GTEST_FOUND}")
    include(cmake/common/External_GTest.cmake)
  endif()
  if(NOT "${GTEST_FOUND}")
    message(FATAL_ERROR "Could not find GTest.")
  endif()
endmacro()

macro(enable_picojson)
  if(NOT "${PicoJSON_FOUND}")
    include(cmake/common/ExternalProjectAdd_PicoJSON.cmake)
  endif()
  if(NOT "${PicoJSON_FOUND}")
    message(FATAL_ERROR "Could not find PicoJSON.")
  endif()
endmacro()
